let sequelize=require('../../config/db');
let Sequelize=require('sequelize');
const agent=sequelize.define('tblAgent',{
    agentId:{
        type:Sequelize.STRING(6),
        primaryKey:true
    },
    agentName:{
        type:Sequelize.STRING(40),
        allowNull:false
    },
    companyName:{
        type:Sequelize.STRING(40),
        allowNull:false
    },
    street:{
        type:Sequelize.STRING(50),
        allowNull:false
    },
    cityId:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    zipCode:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    classification:{
        type:Sequelize.CHAR(1),
        allowNull:false
    },
    warehouseId:{
        type:Sequelize.INTEGER,
        allowNull:true
    },
    paymentTerms:{
        type:Sequelize.DATEONLY,
        allowNull:true
    },
    creditLimit:{
        type:Sequelize.INTEGER,
        allowNull:true
    },
    active:{
        type:Sequelize.BOOLEAN,
        allowNull:false,
        defaultValue: false
    }
});
module.exports={agent};